openapi: 3.1.0
info:
  title: Workcloud Task Management – MyWork API
  version: 1.1.0
  description: |
    External API specification for Workcloud Task Management – MyWork.

    This API covers workforce-facing capabilities only:
    - Feeds & Feed Notes
    - Feed-level operations (claim, reassign, acknowledge, etc.)
    - Real-Time Management (RTM) operations
    - Surveys
    - User management, accounts, sessions, and profile assets

servers:
  - url: https://api.workcloud.example.com/mywork/v1

security:
  - OAuth2: [mywork.read, mywork.write]

tags:
  - name: Feeds
  - name: FeedNotes
  - name: FeedOperations
  - name: Surveys
  - name: RealTimeManagement
  - name: Users
  - name: UserAccounts
  - name: UserSessions
  - name: UserAssets

paths:
  /feeds:
    get:
      tags: [Feeds]
      summary: List feeds
      operationId: listFeeds
      parameters:
        - $ref: '#/components/parameters/PageSize'
        - $ref: '#/components/parameters/PageToken'
      responses:
        '200':
          description: Feed list
          content:
            application/json:
              schema: { $ref: '#/components/schemas/FeedList' }
    post:
      tags: [Feeds]
      summary: Create feed
      operationId: createFeed
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: '#/components/schemas/FeedCreate' }
      responses:
        '201':
          description: Feed created
          content:
            application/json:
              schema: { $ref: '#/components/schemas/Feed' }

  /feeds/{feedId}:
    get:
      tags: [Feeds]
      summary: Get feed
      operationId: getFeed
      parameters: [ { $ref: '#/components/parameters/FeedId' } ]
      responses:
        '200':
          description: Feed
          content:
            application/json:
              schema: { $ref: '#/components/schemas/Feed' }
    patch:
      tags: [Feeds]
      summary: Update feed
      operationId: updateFeed
      parameters: [ { $ref: '#/components/parameters/FeedId' } ]
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: '#/components/schemas/FeedUpdate' }
      responses:
        '200': { description: Feed updated }
    delete:
      tags: [Feeds]
      summary: Delete feed
      operationId: deleteFeed
      parameters: [ { $ref: '#/components/parameters/FeedId' } ]
      responses:
        '204': { description: Feed deleted }

  /feeds/{feedId}/operations:
    post:
      tags: [FeedOperations]
      summary: Perform feed operation
      operationId: performFeedOperation
      parameters: [ { $ref: '#/components/parameters/FeedId' } ]
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: '#/components/schemas/FeedOperationRequest' }
      responses:
        '202': { description: Operation accepted }

  /feeds/{feedId}/notes:
    get:
      tags: [FeedNotes]
      summary: List feed notes
      operationId: listFeedNotes
      parameters: [ { $ref: '#/components/parameters/FeedId' } ]
      responses:
        '200':
          content:
            application/json:
              schema: { $ref: '#/components/schemas/FeedNoteList' }
    post:
      tags: [FeedNotes]
      summary: Create feed note
      operationId: createFeedNote
      parameters: [ { $ref: '#/components/parameters/FeedId' } ]
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: '#/components/schemas/FeedNoteCreate' }
      responses:
        '201': { description: Feed note created }

  /feeds/{feedId}/notes/{noteId}:
    patch:
      tags: [FeedNotes]
      summary: Update feed note
      operationId: updateFeedNote
      parameters:
        - $ref: '#/components/parameters/FeedId'
        - $ref: '#/components/parameters/NoteId'
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: '#/components/schemas/FeedNoteUpdate' }
      responses:
        '200': { description: Feed note updated }
    delete:
      tags: [FeedNotes]
      summary: Delete feed note
      operationId: deleteFeedNote
      parameters:
        - $ref: '#/components/parameters/FeedId'
        - $ref: '#/components/parameters/NoteId'
      responses:
        '204': { description: Feed note deleted }

  /surveys:
    get:
      tags: [Surveys]
      summary: List surveys
      operationId: listSurveys
      responses:
        '200': { description: Survey list }
    post:
      tags: [Surveys]
      summary: Create survey
      operationId: createSurvey
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: '#/components/schemas/SurveyCreate' }
      responses:
        '201': { description: Survey created }

  /surveys/{surveyId}/responses:
    post:
      tags: [Surveys]
      summary: Submit survey response
      operationId: submitSurveyResponse
      parameters: [ { $ref: '#/components/parameters/SurveyId' } ]
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: '#/components/schemas/SurveyResponseCreate' }
      responses:
        '201': { description: Survey response submitted }

  /rtm/operations:
    post:
      tags: [RealTimeManagement]
      summary: Perform RTM operation
      operationId: performRtmOperation
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: '#/components/schemas/RtmOperationRequest' }
      responses:
        '202': { description: RTM operation accepted }

  /users:
    get:
      tags: [Users]
      summary: List users
      operationId: listUsers
      responses:
        '200': { description: User list }

  /users/{userId}:
    get:
      tags: [Users]
      summary: Get user
      operationId: getUser
      parameters: [ { $ref: '#/components/parameters/UserId' } ]
      responses:
        '200': { description: User }

  /users/{userId}/image:
    put:
      tags: [UserAssets]
      summary: Upload user image
      operationId: uploadUserImage
      parameters: [ { $ref: '#/components/parameters/UserId' } ]
      requestBody:
        required: true
        content:
          image/*:
            schema:
              type: string
              format: binary
      responses:
        '200': { description: Image uploaded }

  /sessions/login:
    post:
      tags: [UserSessions]
      summary: Login success event
      operationId: loginSuccess
      responses:
        '200': { description: Login recorded }

  /sessions/logout:
    post:
      tags: [UserSessions]
      summary: Logout
      operationId: logout
      responses:
        '204': { description: Logged out }

components:
  parameters:
    FeedId: { name: feedId, in: path, required: true, schema: { type: string } }
    NoteId: { name: noteId, in: path, required: true, schema: { type: string } }
    SurveyId: { name: surveyId, in: path, required: true, schema: { type: string } }
    UserId: { name: userId, in: path, required: true, schema: { type: string } }
    PageSize: { name: pageSize, in: query, schema: { type: integer } }
    PageToken: { name: pageToken, in: query, schema: { type: string } }

  schemas:
    FeedOperationRequest:
      type: object
      required: [operation]
      properties:
        operation:
          type: string
          enum: [CLAIM, REASSIGN, ACKNOWLEDGE, COMPLETE, ESCALATE]
        payload:
          type: object
          additionalProperties: true

    RtmOperationRequest:
      type: object
      required: [operation]
      properties:
        operation:
          type: string
          enum: [SEND_SURVEY, BROADCAST, NUDGE, ESCALATE, REASSIGN]
        payload:
          type: object
          additionalProperties: true

    Feed:
      type: object
      properties:
        id: { type: string }
        title: { type: string }
        message: { type: string }
        status: { type: string }
        createdAt: { type: string, format: date-time }

    FeedCreate:
      type: object
      required: [title, message]
      properties:
        title: { type: string }
        message: { type: string }

    FeedUpdate:
      type: object
      properties:
        title: { type: string }
        message: { type: string }

    FeedList:
      type: object
      properties:
        items: { type: array, items: { $ref: '#/components/schemas/Feed' } }

    FeedNote:
      type: object
      properties:
        id: { type: string }
        message: { type: string }
        createdAt: { type: string, format: date-time }

    FeedNoteCreate:
      type: object
      required: [message]
      properties:
        message: { type: string }

    FeedNoteUpdate:
      type: object
      properties:
        message: { type: string }

    FeedNoteList:
      type: object
      properties:
        items: { type: array, items: { $ref: '#/components/schemas/FeedNote' } }

    SurveyCreate:
      type: object
      properties:
        title: { type: string }
        questions: { type: array, items: { type: string } }

    SurveyResponseCreate:
      type: object
      properties:
        responses: { type: object, additionalProperties: true }
