/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.8.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.api;

import org.openapitools.model.Feed;
import org.openapitools.model.FeedCreate;
import org.openapitools.model.FeedList;
import org.openapitools.model.FeedNoteCreate;
import org.openapitools.model.FeedNoteList;
import org.openapitools.model.FeedNoteUpdate;
import org.openapitools.model.FeedOperationRequest;
import org.openapitools.model.FeedUpdate;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import javax.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-01-19T21:19:59.650180600+05:30[Asia/Calcutta]", comments = "Generator version: 7.8.0")
@Validated
@Tag(name = "Feeds", description = "the Feeds API")
public interface FeedsApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * POST /feeds : Create feed
     *
     * @param feedCreate  (required)
     * @return Feed created (status code 201)
     */
    @Operation(
        operationId = "createFeed",
        summary = "Create feed",
        tags = { "Feeds" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Feed created", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Feed.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/feeds",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<Feed> createFeed(
        @Parameter(name = "FeedCreate", description = "", required = true) @Valid @RequestBody FeedCreate feedCreate
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"createdAt\" : \"2000-01-23T04:56:07.000+00:00\", \"id\" : \"id\", \"title\" : \"title\", \"message\" : \"message\", \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * POST /feeds/{feedId}/notes : Create feed note
     *
     * @param feedId  (required)
     * @param feedNoteCreate  (required)
     * @return Feed note created (status code 201)
     */
    @Operation(
        operationId = "createFeedNote",
        summary = "Create feed note",
        tags = { "FeedNotes" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Feed note created")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/feeds/{feedId}/notes",
        consumes = { "application/json" }
    )
    
    default ResponseEntity<Void> createFeedNote(
        @Parameter(name = "feedId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("feedId") String feedId,
        @Parameter(name = "FeedNoteCreate", description = "", required = true) @Valid @RequestBody FeedNoteCreate feedNoteCreate
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * DELETE /feeds/{feedId} : Delete feed
     *
     * @param feedId  (required)
     * @return Feed deleted (status code 204)
     */
    @Operation(
        operationId = "deleteFeed",
        summary = "Delete feed",
        tags = { "Feeds" },
        responses = {
            @ApiResponse(responseCode = "204", description = "Feed deleted")
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = "/feeds/{feedId}"
    )
    
    default ResponseEntity<Void> deleteFeed(
        @Parameter(name = "feedId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("feedId") String feedId
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * DELETE /feeds/{feedId}/notes/{noteId} : Delete feed note
     *
     * @param feedId  (required)
     * @param noteId  (required)
     * @return Feed note deleted (status code 204)
     */
    @Operation(
        operationId = "deleteFeedNote",
        summary = "Delete feed note",
        tags = { "FeedNotes" },
        responses = {
            @ApiResponse(responseCode = "204", description = "Feed note deleted")
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = "/feeds/{feedId}/notes/{noteId}"
    )
    
    default ResponseEntity<Void> deleteFeedNote(
        @Parameter(name = "feedId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("feedId") String feedId,
        @Parameter(name = "noteId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("noteId") String noteId
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /feeds/{feedId} : Get feed
     *
     * @param feedId  (required)
     * @return Feed (status code 200)
     */
    @Operation(
        operationId = "getFeed",
        summary = "Get feed",
        tags = { "Feeds" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Feed", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Feed.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/feeds/{feedId}",
        produces = { "application/json" }
    )
    
    default ResponseEntity<Feed> getFeed(
        @Parameter(name = "feedId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("feedId") String feedId
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"createdAt\" : \"2000-01-23T04:56:07.000+00:00\", \"id\" : \"id\", \"title\" : \"title\", \"message\" : \"message\", \"status\" : \"status\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /feeds/{feedId}/notes : List feed notes
     *
     * @param feedId  (required)
     * @return  (status code 200)
     */
    @Operation(
        operationId = "listFeedNotes",
        summary = "List feed notes",
        tags = { "FeedNotes" },
        responses = {
            @ApiResponse(responseCode = "200", description = "", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = FeedNoteList.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/feeds/{feedId}/notes",
        produces = { "application/json" }
    )
    
    default ResponseEntity<FeedNoteList> listFeedNotes(
        @Parameter(name = "feedId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("feedId") String feedId
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"items\" : [ { \"createdAt\" : \"2000-01-23T04:56:07.000+00:00\", \"id\" : \"id\", \"message\" : \"message\" }, { \"createdAt\" : \"2000-01-23T04:56:07.000+00:00\", \"id\" : \"id\", \"message\" : \"message\" } ] }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /feeds : List feeds
     *
     * @param pageSize  (optional)
     * @param pageToken  (optional)
     * @return Feed list (status code 200)
     */
    @Operation(
        operationId = "listFeeds",
        summary = "List feeds",
        tags = { "Feeds" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Feed list", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = FeedList.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/feeds",
        produces = { "application/json" }
    )
    
    default ResponseEntity<FeedList> listFeeds(
        @Parameter(name = "pageSize", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "pageSize", required = false) Integer pageSize,
        @Parameter(name = "pageToken", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "pageToken", required = false) String pageToken
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"items\" : [ { \"createdAt\" : \"2000-01-23T04:56:07.000+00:00\", \"id\" : \"id\", \"title\" : \"title\", \"message\" : \"message\", \"status\" : \"status\" }, { \"createdAt\" : \"2000-01-23T04:56:07.000+00:00\", \"id\" : \"id\", \"title\" : \"title\", \"message\" : \"message\", \"status\" : \"status\" } ] }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * POST /feeds/{feedId}/operations : Perform feed operation
     *
     * @param feedId  (required)
     * @param feedOperationRequest  (required)
     * @return Operation accepted (status code 202)
     */
    @Operation(
        operationId = "performFeedOperation",
        summary = "Perform feed operation",
        tags = { "FeedOperations" },
        responses = {
            @ApiResponse(responseCode = "202", description = "Operation accepted")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/feeds/{feedId}/operations",
        consumes = { "application/json" }
    )
    
    default ResponseEntity<Void> performFeedOperation(
        @Parameter(name = "feedId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("feedId") String feedId,
        @Parameter(name = "FeedOperationRequest", description = "", required = true) @Valid @RequestBody FeedOperationRequest feedOperationRequest
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * PATCH /feeds/{feedId} : Update feed
     *
     * @param feedId  (required)
     * @param feedUpdate  (required)
     * @return Feed updated (status code 200)
     */
    @Operation(
        operationId = "updateFeed",
        summary = "Update feed",
        tags = { "Feeds" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Feed updated")
        }
    )
    @RequestMapping(
        method = RequestMethod.PATCH,
        value = "/feeds/{feedId}",
        consumes = { "application/json" }
    )
    
    default ResponseEntity<Void> updateFeed(
        @Parameter(name = "feedId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("feedId") String feedId,
        @Parameter(name = "FeedUpdate", description = "", required = true) @Valid @RequestBody FeedUpdate feedUpdate
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * PATCH /feeds/{feedId}/notes/{noteId} : Update feed note
     *
     * @param feedId  (required)
     * @param noteId  (required)
     * @param feedNoteUpdate  (required)
     * @return Feed note updated (status code 200)
     */
    @Operation(
        operationId = "updateFeedNote",
        summary = "Update feed note",
        tags = { "FeedNotes" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Feed note updated")
        }
    )
    @RequestMapping(
        method = RequestMethod.PATCH,
        value = "/feeds/{feedId}/notes/{noteId}",
        consumes = { "application/json" }
    )
    
    default ResponseEntity<Void> updateFeedNote(
        @Parameter(name = "feedId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("feedId") String feedId,
        @Parameter(name = "noteId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("noteId") String noteId,
        @Parameter(name = "FeedNoteUpdate", description = "", required = true) @Valid @RequestBody FeedNoteUpdate feedNoteUpdate
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
