/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.8.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.api;

import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import javax.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-01-19T21:19:59.650180600+05:30[Asia/Calcutta]", comments = "Generator version: 7.8.0")
@Validated
@Tag(name = "Users", description = "the Users API")
public interface UsersApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * GET /users/{userId} : Get user
     *
     * @param userId  (required)
     * @return User (status code 200)
     */
    @Operation(
        operationId = "getUser",
        summary = "Get user",
        tags = { "Users" },
        responses = {
            @ApiResponse(responseCode = "200", description = "User")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/users/{userId}"
    )
    
    default ResponseEntity<Void> getUser(
        @Parameter(name = "userId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("userId") String userId
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /users : List users
     *
     * @return User list (status code 200)
     */
    @Operation(
        operationId = "listUsers",
        summary = "List users",
        tags = { "Users" },
        responses = {
            @ApiResponse(responseCode = "200", description = "User list")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/users"
    )
    
    default ResponseEntity<Void> listUsers(
        
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * PUT /users/{userId}/image : Upload user image
     *
     * @param userId  (required)
     * @param body  (required)
     * @return Image uploaded (status code 200)
     */
    @Operation(
        operationId = "uploadUserImage",
        summary = "Upload user image",
        tags = { "UserAssets" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Image uploaded")
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = "/users/{userId}/image",
        consumes = { "image/*" }
    )
    
    default ResponseEntity<Void> uploadUserImage(
        @Parameter(name = "userId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("userId") String userId,
        @Parameter(name = "body", description = "", required = true) @Valid @RequestBody org.springframework.core.io.Resource body
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
