/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.8.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.api;

import org.openapitools.model.RtmOperationRequest;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import javax.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-01-19T21:19:59.650180600+05:30[Asia/Calcutta]", comments = "Generator version: 7.8.0")
@Validated
@Tag(name = "RealTimeManagement", description = "the RealTimeManagement API")
public interface RtmApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * POST /rtm/operations : Perform RTM operation
     *
     * @param rtmOperationRequest  (required)
     * @return RTM operation accepted (status code 202)
     */
    @Operation(
        operationId = "performRtmOperation",
        summary = "Perform RTM operation",
        tags = { "RealTimeManagement" },
        responses = {
            @ApiResponse(responseCode = "202", description = "RTM operation accepted")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/rtm/operations",
        consumes = { "application/json" }
    )
    
    default ResponseEntity<Void> performRtmOperation(
        @Parameter(name = "RtmOperationRequest", description = "", required = true) @Valid @RequestBody RtmOperationRequest rtmOperationRequest
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
