/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.8.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.api;

import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import javax.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-01-19T21:19:59.650180600+05:30[Asia/Calcutta]", comments = "Generator version: 7.8.0")
@Validated
@Tag(name = "UserSessions", description = "the UserSessions API")
public interface SessionsApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * POST /sessions/login : Login success event
     *
     * @return Login recorded (status code 200)
     */
    @Operation(
        operationId = "loginSuccess",
        summary = "Login success event",
        tags = { "UserSessions" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Login recorded")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/sessions/login"
    )
    
    default ResponseEntity<Void> loginSuccess(
        
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * POST /sessions/logout : Logout
     *
     * @return Logged out (status code 204)
     */
    @Operation(
        operationId = "logout",
        summary = "Logout",
        tags = { "UserSessions" },
        responses = {
            @ApiResponse(responseCode = "204", description = "Logged out")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/sessions/logout"
    )
    
    default ResponseEntity<Void> logout(
        
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
