package com.workcloud.wtm.feeds.domain.model;

import java.time.OffsetDateTime;
import java.util.Objects;

/**
 * Domain entity representing a Feed in the system.
 * This is the core business entity following Domain-Driven Design principles.
 */
public class Feed {
    private String id;
    private String title;
    private String message;
    private FeedStatus status;
    private OffsetDateTime createdAt;

    private Feed() {
        // Private constructor for immutability
    }

    public Feed(String id, String title, String message, FeedStatus status, OffsetDateTime createdAt) {
        this.id = id;
        this.title = title;
        this.message = message;
        this.status = status;
        this.createdAt = createdAt;
    }

    public static Feed create(String title, String message) {
        return new Feed(
            null, // ID will be generated by repository
            title,
            message,
            FeedStatus.PENDING,
            OffsetDateTime.now()
        );
    }

    public void claim() {
        if (this.status != FeedStatus.PENDING) {
            throw new IllegalStateException("Only pending feeds can be claimed");
        }
        this.status = FeedStatus.CLAIMED;
    }

    public void acknowledge() {
        if (this.status != FeedStatus.CLAIMED) {
            throw new IllegalStateException("Only claimed feeds can be acknowledged");
        }
        this.status = FeedStatus.ACKNOWLEDGED;
    }

    public void complete() {
        if (this.status == FeedStatus.COMPLETED) {
            throw new IllegalStateException("Feed is already completed");
        }
        this.status = FeedStatus.COMPLETED;
    }

    public void escalate() {
        this.status = FeedStatus.ESCALATED;
    }

    public void reassign() {
        if (this.status == FeedStatus.COMPLETED) {
            throw new IllegalStateException("Completed feeds cannot be reassigned");
        }
        this.status = FeedStatus.PENDING;
    }

    public void update(String title, String message) {
        if (title != null) {
            this.title = title;
        }
        if (message != null) {
            this.message = message;
        }
    }

    // Getters
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public String getMessage() {
        return message;
    }

    public FeedStatus getStatus() {
        return status;
    }

    public OffsetDateTime getCreatedAt() {
        return createdAt;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Feed feed = (Feed) o;
        return Objects.equals(id, feed.id);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id);
    }
}
