/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.8.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.api;

import org.openapitools.model.SurveyCreate;
import org.openapitools.model.SurveyResponseCreate;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import javax.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-01-19T21:19:59.650180600+05:30[Asia/Calcutta]", comments = "Generator version: 7.8.0")
@Validated
@Tag(name = "Surveys", description = "the Surveys API")
public interface SurveysApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * POST /surveys : Create survey
     *
     * @param surveyCreate  (required)
     * @return Survey created (status code 201)
     */
    @Operation(
        operationId = "createSurvey",
        summary = "Create survey",
        tags = { "Surveys" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Survey created")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/surveys",
        consumes = { "application/json" }
    )
    
    default ResponseEntity<Void> createSurvey(
        @Parameter(name = "SurveyCreate", description = "", required = true) @Valid @RequestBody SurveyCreate surveyCreate
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /surveys : List surveys
     *
     * @return Survey list (status code 200)
     */
    @Operation(
        operationId = "listSurveys",
        summary = "List surveys",
        tags = { "Surveys" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Survey list")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/surveys"
    )
    
    default ResponseEntity<Void> listSurveys(
        
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * POST /surveys/{surveyId}/responses : Submit survey response
     *
     * @param surveyId  (required)
     * @param surveyResponseCreate  (required)
     * @return Survey response submitted (status code 201)
     */
    @Operation(
        operationId = "submitSurveyResponse",
        summary = "Submit survey response",
        tags = { "Surveys" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Survey response submitted")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/surveys/{surveyId}/responses",
        consumes = { "application/json" }
    )
    
    default ResponseEntity<Void> submitSurveyResponse(
        @Parameter(name = "surveyId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("surveyId") String surveyId,
        @Parameter(name = "SurveyResponseCreate", description = "", required = true) @Valid @RequestBody SurveyResponseCreate surveyResponseCreate
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
